# Site settings
title: Code for Philly Slides
email: ben@codeforphilly.org

description: > # this means to ignore newlines until "baseurl:"
  Slide decks for Code for Philly!

baseurl: "/slides"
url: "https:/CfABrigadePhiladelphia.github.io"

# Build settings
markdown: kramdown
markdown_ext: ignoreme

collections:
    slides:
        output: true
        permalink: "/:path/"
